# Generated by Django 3.0.8 on 2020-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url_youtube', models.URLField()),
                ('description', models.TextField()),
                ('origins', models.CharField(max_length=10)),
            ],
        ),
    ]
